import { Header } from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { classNames } from '@/lib'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <link
        href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.11.0/css/flag-icons.min.css"
        rel="stylesheet"
      />
      <title>En memoria de Isabel Da Paixao</title>
    </head>
      <body className={classNames(inter.className, 'bg-neutral-950')}>
      <Header/>
      {children}
      </body>
    </html>
  )
}
